[#enhanced-get]
== Enhanced GET

=== General

This is a lightweight protocol which allows simple clients to
efficiently discover and download changes in the targeted resource.

It has many similarities to WebDAV sync and for a server could be
implemented as an extension of the specification.

In this protocol the client MUST include the Prefer header field
preference "subscribe-enhanced-get". If a sync token is available it
is passed as a Sync-Token header field.

The resource is treated as a set of individual events each of which
may be updated or deleted separately. The client will first fetch
the entire iCalendar file.  On subsequent requests it uses the Prefer
header field and a Sync-Token header field to indicate that it wants a set
of changes since the last fetch.

If no Sync-Token header field is supplied the server SHOULD
respond with a full set of data. Otherwise, if the token is valid, it SHOULD return with a set of changed entities.

In both cases the server should set the Preference-Applied header field and a new Sync-Token header field value.


=== Deletions

When an entity (VEVENT, VTODO or other valid top-level component) is
deleted from the source data the server needs to be able to inform a
client of the deletion.  This specification introduces a new value
for the STATUS property of DELETED.

On the first enhanced GET after the entity has been deleted a
skeleton, but valid, entity will be returned with STATUS: DELETED.
The receiving client is free to remove the entity or update it's
STATUS property.

On subsequent fetches the entity will not be returned.

=== Handling of invalid sync tokens

When a server receives an invalid token it MUST return a 409 status (Conflict).  The server MAY choose to return an error
message in the body.

The client SHOULD respond to this error by restarting the interaction
from scratch, i.e. retrieve the full set of data then poll for
updates.

=== Paging the response

A client may explicitly request a limit on the size of the response
by specifying the Prefer header field preference "limit=n" where n is
the number of components.

When a server receives a request specifying such a limit it SHOULD
limit the response to that number of components.  If the limit causes
a truncation in the response the server should respond with a
Preference-Applied header specifying the limit that was applied
and return a sync token which may be used to retrieve the next batch of data.

This allows the client to immediately resubmit a
request for the next batch using the updated token.

A server MAY choose to limit the response size.  The behavior SHOULD
be as if the client had provided a preference for that size -
allowing the client to retrieve the full set of data in batches.

=== Caching of responses

To enable proper caching of responses the server SHOULD provide a
VARY header field in responses that names the Prefer and Sync-Token header fields
along with any other that are appropriate.

Clients should order the preferences as following so that
identical responses can be identified:

  * subscribe-enhanced-get
  * limit

=== Examples

[example]
--
This is an example of the initial request and response from a server
that supports the enhanced GET method. Note the use of the Vary header so a caching proxy can key off the client's Sync-Token and preference.

[source]
----
    >> Request <<

    GET /events.ics HTTP/1.1
    Host: example.com
    Accept: text/calendar
    Prefer: subscribe-enhanced-get

    >> Response <<

    HTTP/1.1 200 OK
    Content-Length: xxxx
    Sync-Token: "data:,1234567"
    Preference-Applied: subscribe-enhanced-get
    Vary: Prefer, Sync-Token

    BEGIN:VCALENDAR:
    ?  /* full feed */
    END:VCALENDAR
----
--


[example]
--
This is an example of the subsequent request and response when no
changes have occurred.

[source]
----
    >> Request <<

    GET /events.ics HTTP/1.1
    Host: example.com
    Accept: text/calendar
    Prefer: subscribe-enhanced-get
    Sync-Token: "data:,1234567"

    >> Response <<

    HTTP/1.1 304 Not Modified
    Content-Length: 0
    Sync-Token: "data:,1234567"
    Preference-Applied: subscribe-enhanced-get
    Vary: Prefer, Sync-Token
----
--


[example]
--
This is an example of the subsequent request and response for
an old or invalid token.

[source]
----
>> Request <<

    GET /events.ics HTTP/1.1
    Host: example.com
    Accept: text/calendar
    Sync-Token: "data:,1234567"
    Prefer: subscribe-enhanced-get

    >> Response <<

    HTTP/1.1 409 Conflict
    Content-Length: xxxx
    Preference-Applied: subscribe-enhanced-get

----
--

[example]
--
This is an example of the subsequent request and response when
changes have occurred.

[source]
----
>> Request <<

    GET /events.ics HTTP/1.1
    Host: example.com
    Accept: text/calendar
    Sync-Token: "data:,1234567"
    Prefer: subscribe-enhanced-get

    >> Response <<

    HTTP/1.1 200 OK
    Content-Type: text/calendar
    Vary: Prefer, Sync-Token
    Sync-Token: "data:,4567890"
    Preference-Applied: subscribe-enhanced-get

    BEGIN:VCALENDAR:
    ...  only new/changed events
    ...  deleted events have STATUS:DELETED
    END:VCALENDAR
----
--
