== Link relations

=== General

This clause defines a number of new link relations required to
facilitate subscription upgrades.

[[la-subscribe-caldav]]
=== subscribe-caldav

This specifies an access point which is a full implementation of
caldav but requires no authentication.  The end point allows the full
range of reports as defined by the CalDAV specification.

The client MUST follow the specification to determine exactly what
operations are allowed on the access point - for example to determine
if sync-report is supported.

The URL MAY include some form of token to allow write access to the
targeted collection.  The client must check it's permissions to
determine whether or not it has been granted write access.


[[la-subscribe-caldav-auth]]
=== subscribe-caldav-auth


This specifies an access point which is a full implementation of
caldav and requires authentication.  This may allow read-write access
to the resource.

The client MUST follow the specification to determine exactly what
operations are allowed on the access point -- for example to determine
if sync-report is supported.


[[la-subscribe-webdav-sync]]
=== subscribe-webdav-sync

This specifies an access point which supports only webdav sync.

This allows the client to issue a sync-report on the resource to
obtain updates.

NOTE: say something about initial startup - use ics to populate?
Initial token?

The client MUST follow that specification.



[[la-subscribe-enhanced-get]]
=== subscribe-enhanced-get

This specifies an access point which supports something new.

The client MUST follow that specification.

